spring:
  jwt:
    expiration:
      access-token: 21600000
      refresh-token: 86400000
  datasource:
    url: jdbc:mysql://localhost:3306/ttak?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /v3/api-docs  # API 문서 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
  info:
    title: My REST API
    description: Some custom description of API.
    version: 1.0
    license:
      name: License of API
      url: API license URL


