spring:
  jwt:
    expiration:
      access-token: 31536000 #60*60*24*365
      refresh-token: 315360000 #60*60*24*365*10
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000
  datasource:
    url: jdbc:mysql://localhost:3306/ttak?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    import:
      - classpath:/application-private.yml

springdoc:
  api-docs:
    path: /v3/api-docs  # API 문서 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
  info:
    title: My REST API
    description: Some custom description of API.
    version: 1.0
    license:
      name: License of API
      url: API license URL


